# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa302ffd4159db98278da2b805fbb9364f7be1de0e45165962f7368aa8619b3536e73e4c4e0c561fd10380215dce16c3c5568d466f54ad216bd172689571dd21

test:
  secret_key_base: d9ab4b5e682f548f7f96c30cf4c653fa623fb47de105cae98fd5b5f6905addf17dc425f202afe83f8ff6e36eb649617040caf69f7ff9deef01215cadbded984b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
